#!/bin/bash
# Build everything Etherscan verification needs into contract/verify/:
#
#   Grinding.input.json       Standard-JSON-Input for the implementation
#   ERC1967Proxy.input.json   Standard-JSON-Input for the proxy
#   Grinding.flat.sol         flattened single-file sources, for the
#   ERC1967Proxy.flat.sol     "single file" upload method
#   constructor-args.txt      the proxy's ABI-encoded constructor arguments,
#                             extracted from the latest broadcast when one
#                             exists (pass a chain id to pick which)
#   README.txt                compiler settings and the exact commands
#
# The implementation has no constructor arguments. The proxy takes
# (implementation address, initialize calldata); once both are verified,
# Etherscan's "is this a proxy?" detection links them and exposes
# Read/Write as Proxy.
#
#   ./verify-bundle.sh [chainid]     # chainid picks the broadcast, default 1

set -euo pipefail
cd "$(dirname "$0")"

CHAIN="${1:-1}"
OUT=verify
PROXY_SRC=lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol
ZERO=0x0000000000000000000000000000000000000000
mkdir -p "$OUT"

forge build >/dev/null

forge flatten src/Grinding.sol -o "$OUT/Grinding.flat.sol" >/dev/null
forge flatten "$PROXY_SRC" -o "$OUT/ERC1967Proxy.flat.sol" >/dev/null
forge verify-contract --show-standard-json-input "$ZERO" src/Grinding.sol:Grinding \
    > "$OUT/Grinding.input.json"
forge verify-contract --show-standard-json-input "$ZERO" "$PROXY_SRC:ERC1967Proxy" \
    > "$OUT/ERC1967Proxy.input.json"

# the proxy's constructor args, straight from the deployment record
BROADCAST="broadcast/Grinding.s.sol/$CHAIN/run-latest.json"
if [ -f "$BROADCAST" ]; then
    python3 - "$BROADCAST" > "$OUT/constructor-args.txt" <<'EOF'
import json, sys
run = json.load(open(sys.argv[1]))
for tx in run["transactions"]:
    if tx.get("contractName") == "ERC1967Proxy" and tx.get("transactionType") == "CREATE":
        impl, data = tx["arguments"]
        print("implementation:", impl)
        print("initialize calldata:", data)
        import subprocess
        enc = subprocess.run(["cast", "abi-encode", "constructor(address,bytes)", impl, data],
                             capture_output=True, text=True).stdout.strip()
        print("abi-encoded constructor args (what Etherscan wants, without 0x):")
        print(enc.removeprefix("0x"))
        break
else:
    print("no ERC1967Proxy CREATE found in", sys.argv[1])
EOF
    echo "constructor args extracted from $BROADCAST"
else
    echo "no broadcast for chain $CHAIN yet; constructor-args.txt not written" >&2
fi

# the settings the manual form asks for, read from the build itself
SOLC=$(forge config --json | python3 -c "import json,sys; print(json.load(sys.stdin)['solc'])")
EVM=$(forge config --json | python3 -c "import json,sys; print(json.load(sys.stdin)['evm_version'])")
OPT=$(forge config --json | python3 -c "import json,sys; c=json.load(sys.stdin); print(f\"{'Yes' if c['optimizer'] else 'No'} ({c['optimizer_runs']} runs)\")")

cat > "$OUT/README.txt" <<EOF
Etherscan verification bundle — generated by verify-bundle.sh

Compiler:        v$SOLC
Optimization:    $OPT
EVM version:     $EVM
License:         MIT

Preferred: automatic, at deploy time
  ETHERSCAN_API_KEY=... forge script script/Grinding.s.sol:Deploy \\
      --rpc-url \$RPC --broadcast --verify

Post-hoc, from the command line
  forge verify-contract --watch --chain $CHAIN \\
      \$IMPLEMENTATION src/Grinding.sol:Grinding
  forge verify-contract --watch --chain $CHAIN \\
      --constructor-args \$(tail -1 constructor-args.txt | sed 's/^/0x/') \\
      \$PROXY $PROXY_SRC:ERC1967Proxy

Manual, on etherscan.io ("Verify & Publish")
  - method "Solidity (Standard-Json-Input)": upload Grinding.input.json for
    the implementation address, ERC1967Proxy.input.json for the proxy
    address; the proxy also needs the constructor arguments from
    constructor-args.txt (final line)
  - or method "Solidity (Single file)": paste the .flat.sol files with the
    compiler settings above. Flattening changes the metadata hash, so this
    verifies as a "partial match" — the JSON files give an exact match

After both verify: on the proxy's Etherscan page use
"More Options > Is this a proxy?" so Read/Write as Proxy appears.
EOF

echo "bundle in contract/$OUT/"
ls -la "$OUT"
